using Deckster.Core.Games.Idiot;
using Deckster.Core.Games.Common;
using System;
using System.Diagnostics;
using Deckster.Core.Communication;
using Deckster.Core.Protocol;
using Deckster.Core.Extensions;

namespace Deckster.Client.Games.Idiot;

/**
 * Autogenerated by really, really eager small hamsters.
*/

[DebuggerDisplay("IdiotClient {PlayerData}")]
public class IdiotClient(IClientChannel channel) : GameClient(channel)
{
    public event Action<ItsTimeToSwapCardsNotification>? ItsTimeToSwapCards;
    public event Action<PlayerIsReadyNotification>? PlayerIsReady;
    public event Action<GameStartedNotification>? GameHasStarted;
    public event Action<GameEndedNotification>? GameEnded;
    public event Action<ItsYourTurnNotification>? ItsYourTurn;
    public event Action<PlayerDrewCardsNotification>? PlayerDrewCards;
    public event Action<PlayerPutCardsNotification>? PlayerPutCards;
    public event Action<DiscardPileFlushedNotification>? DiscardPileFlushed;
    public event Action<PlayerIsDoneNotification>? PlayerIsDone;
    public event Action<PlayerAttemptedPuttingCardNotification>? PlayerAttemptedPuttingCard;
    public event Action<PlayerPulledInDiscardPileNotification>? PlayerPulledInDiscardPile;
    public event Action<PlayerSwappedCardsNotification>? PlayerSwappedCards;

    public Task<EmptyResponse> IamReadyAsync(IamReadyRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<EmptyResponse>(request, false, cancellationToken);
    }

    public Task<SwapCardsResponse> SwapCardsAsync(SwapCardsRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<SwapCardsResponse>(request, false, cancellationToken);
    }

    public Task<EmptyResponse> PutCardsFromHandAsync(PutCardsFromHandRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<EmptyResponse>(request, false, cancellationToken);
    }

    public Task<EmptyResponse> PutCardsFacingUpAsync(PutCardsFacingUpRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<EmptyResponse>(request, false, cancellationToken);
    }

    public Task<PutBlindCardResponse> PutCardFacingDownAsync(PutCardFacingDownRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<PutBlindCardResponse>(request, false, cancellationToken);
    }

    public Task<PutBlindCardResponse> PutChanceCardAsync(PutChanceCardRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<PutBlindCardResponse>(request, false, cancellationToken);
    }

    public Task<PullInResponse> PullInDiscardPileAsync(PullInDiscardPileRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<PullInResponse>(request, false, cancellationToken);
    }

    public Task<DrawCardsResponse> DrawCardsAsync(DrawCardsRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<DrawCardsResponse>(request, false, cancellationToken);
    }

    protected override void OnNotification(DecksterNotification notification)
    {
        try
        {
            switch (notification)
            {
                case ItsTimeToSwapCardsNotification m:
                    ItsTimeToSwapCards?.Invoke(m);
                    return;
                case PlayerIsReadyNotification m:
                    PlayerIsReady?.Invoke(m);
                    return;
                case GameStartedNotification m:
                    GameHasStarted?.Invoke(m);
                    return;
                case GameEndedNotification m:
                    GameEnded?.Invoke(m);
                    return;
                case ItsYourTurnNotification m:
                    ItsYourTurn?.Invoke(m);
                    return;
                case PlayerDrewCardsNotification m:
                    PlayerDrewCards?.Invoke(m);
                    return;
                case PlayerPutCardsNotification m:
                    PlayerPutCards?.Invoke(m);
                    return;
                case DiscardPileFlushedNotification m:
                    DiscardPileFlushed?.Invoke(m);
                    return;
                case PlayerIsDoneNotification m:
                    PlayerIsDone?.Invoke(m);
                    return;
                case PlayerAttemptedPuttingCardNotification m:
                    PlayerAttemptedPuttingCard?.Invoke(m);
                    return;
                case PlayerPulledInDiscardPileNotification m:
                    PlayerPulledInDiscardPile?.Invoke(m);
                    return;
                case PlayerSwappedCardsNotification m:
                    PlayerSwappedCards?.Invoke(m);
                    return;
                default:
                    return;
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }
}

public static class IdiotClientConveniences
{
    public static async Task IamReadyAsync(this IdiotClient self, CancellationToken cancellationToken = default)
    {
        var request = new IamReadyRequest{  };
        var response = await self.SendAsync<EmptyResponse>(request, true, cancellationToken);
    }
    public static async Task<(Card cardNowOnHand, Card cardNowFacingUp)> SwapCardsAsync(this IdiotClient self, Card cardOnHand, Card cardFacingUp, CancellationToken cancellationToken = default)
    {
        var request = new SwapCardsRequest{ CardOnHand = cardOnHand, CardFacingUp = cardFacingUp };
        var response = await self.SendAsync<SwapCardsResponse>(request, true, cancellationToken);
        return (response.CardNowOnHand, response.CardNowFacingUp);
    }
    public static async Task PutCardsFromHandAsync(this IdiotClient self, Card[] cards, CancellationToken cancellationToken = default)
    {
        var request = new PutCardsFromHandRequest{ Cards = cards };
        var response = await self.SendAsync<EmptyResponse>(request, true, cancellationToken);
    }
    public static async Task PutCardsFacingUpAsync(this IdiotClient self, Card[] cards, CancellationToken cancellationToken = default)
    {
        var request = new PutCardsFacingUpRequest{ Cards = cards };
        var response = await self.SendAsync<EmptyResponse>(request, true, cancellationToken);
    }
    public static async Task<(Card attemptedCard, Card[] pullInCards)> PutCardFacingDownAsync(this IdiotClient self, int index, CancellationToken cancellationToken = default)
    {
        var request = new PutCardFacingDownRequest{ Index = index };
        var response = await self.SendAsync<PutBlindCardResponse>(request, true, cancellationToken);
        return (response.AttemptedCard, response.PullInCards);
    }
    public static async Task<(Card attemptedCard, Card[] pullInCards)> PutChanceCardAsync(this IdiotClient self, CancellationToken cancellationToken = default)
    {
        var request = new PutChanceCardRequest{  };
        var response = await self.SendAsync<PutBlindCardResponse>(request, true, cancellationToken);
        return (response.AttemptedCard, response.PullInCards);
    }
    public static async Task<Card[]> PullInDiscardPileAsync(this IdiotClient self, CancellationToken cancellationToken = default)
    {
        var request = new PullInDiscardPileRequest{  };
        var response = await self.SendAsync<PullInResponse>(request, true, cancellationToken);
        return response.Cards;
    }
    public static async Task<Card[]> DrawCardsAsync(this IdiotClient self, int numberOfCards, CancellationToken cancellationToken = default)
    {
        var request = new DrawCardsRequest{ NumberOfCards = numberOfCards };
        var response = await self.SendAsync<DrawCardsResponse>(request, true, cancellationToken);
        return response.Cards;
    }
}

public static class IdiotClientDecksterClientExtensions
{
    public static GameApi<IdiotClient> Idiot(this DecksterClient client)
    {
        return new GameApi<IdiotClient>(client.BaseUri.Append("idiot"), client.Token, c => new IdiotClient(c));
    }
}
