using Deckster.Core.Games.CrazyEights;
using Deckster.Core.Games.Common;
using System.Diagnostics;
using Deckster.Core.Communication;
using Deckster.Core.Protocol;
using Deckster.Core.Extensions;

namespace Deckster.Client.Games.CrazyEights;

/**
 * Autogenerated by really, really eager small hamsters.
*/

[DebuggerDisplay("CrazyEightsClient {PlayerData}")]
public class CrazyEightsClient(IClientChannel channel) : GameClient(channel)
{
    public event Action<GameStartedNotification>? GameStarted;
    public event Action<PlayerDrewCardNotification>? PlayerDrewCard;
    public event Action<ItsYourTurnNotification>? ItsYourTurn;
    public event Action<PlayerPassedNotification>? PlayerPassed;
    public event Action<PlayerPutCardNotification>? PlayerPutCard;
    public event Action<PlayerPutEightNotification>? PlayerPutEight;
    public event Action<GameEndedNotification>? GameEnded;
    public event Action<PlayerIsDoneNotification>? PlayerIsDone;

    public Task<PlayerViewOfGame> PutCardAsync(PutCardRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<PlayerViewOfGame>(request, false, cancellationToken);
    }

    public Task<PlayerViewOfGame> PutEightAsync(PutEightRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<PlayerViewOfGame>(request, false, cancellationToken);
    }

    public Task<CardResponse> DrawCardAsync(DrawCardRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<CardResponse>(request, false, cancellationToken);
    }

    public Task<EmptyResponse> PassAsync(PassRequest request, CancellationToken cancellationToken = default)
    {
        return SendAsync<EmptyResponse>(request, false, cancellationToken);
    }

    protected override void OnNotification(DecksterNotification notification)
    {
        try
        {
            switch (notification)
            {
                case GameStartedNotification m:
                    GameStarted?.Invoke(m);
                    return;
                case PlayerDrewCardNotification m:
                    PlayerDrewCard?.Invoke(m);
                    return;
                case ItsYourTurnNotification m:
                    ItsYourTurn?.Invoke(m);
                    return;
                case PlayerPassedNotification m:
                    PlayerPassed?.Invoke(m);
                    return;
                case PlayerPutCardNotification m:
                    PlayerPutCard?.Invoke(m);
                    return;
                case PlayerPutEightNotification m:
                    PlayerPutEight?.Invoke(m);
                    return;
                case GameEndedNotification m:
                    GameEnded?.Invoke(m);
                    return;
                case PlayerIsDoneNotification m:
                    PlayerIsDone?.Invoke(m);
                    return;
                default:
                    return;
            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }
}

public static class CrazyEightsClientConveniences
{
    public static async Task<(List<Card> cards, Card topOfPile, Suit currentSuit, int stockPileCount, int discardPileCount, List<OtherCrazyEightsPlayer> otherPlayers)> PutCardAsync(this CrazyEightsClient self, Card card, CancellationToken cancellationToken = default)
    {
        var request = new PutCardRequest{ Card = card };
        var response = await self.SendAsync<PlayerViewOfGame>(request, true, cancellationToken);
        return (response.Cards, response.TopOfPile, response.CurrentSuit, response.StockPileCount, response.DiscardPileCount, response.OtherPlayers);
    }
    public static async Task<(List<Card> cards, Card topOfPile, Suit currentSuit, int stockPileCount, int discardPileCount, List<OtherCrazyEightsPlayer> otherPlayers)> PutEightAsync(this CrazyEightsClient self, Card card, Suit newSuit, CancellationToken cancellationToken = default)
    {
        var request = new PutEightRequest{ Card = card, NewSuit = newSuit };
        var response = await self.SendAsync<PlayerViewOfGame>(request, true, cancellationToken);
        return (response.Cards, response.TopOfPile, response.CurrentSuit, response.StockPileCount, response.DiscardPileCount, response.OtherPlayers);
    }
    public static async Task<Card> DrawCardAsync(this CrazyEightsClient self, CancellationToken cancellationToken = default)
    {
        var request = new DrawCardRequest{  };
        var response = await self.SendAsync<CardResponse>(request, true, cancellationToken);
        return response.Card;
    }
    public static async Task PassAsync(this CrazyEightsClient self, CancellationToken cancellationToken = default)
    {
        var request = new PassRequest{  };
        var response = await self.SendAsync<EmptyResponse>(request, true, cancellationToken);
    }
}

public static class CrazyEightsClientDecksterClientExtensions
{
    public static GameApi<CrazyEightsClient> CrazyEights(this DecksterClient client)
    {
        return new GameApi<CrazyEightsClient>(client.BaseUri.Append("crazyeights"), client.Token, c => new CrazyEightsClient(c));
    }
}
