/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = CrazyEightsGameEndedNotification::class, name = "CrazyEights.GameEndedNotification"),
    JsonSubTypes.Type(value = CrazyEightsGameStartedNotification::class, name = "CrazyEights.GameStartedNotification"),
    JsonSubTypes.Type(value = CrazyEightsItsYourTurnNotification::class, name = "CrazyEights.ItsYourTurnNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerDrewCardNotification::class, name = "CrazyEights.PlayerDrewCardNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPassedNotification::class, name = "CrazyEights.PlayerPassedNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPutCardNotification::class, name = "CrazyEights.PlayerPutCardNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPutEightNotification::class, name = "CrazyEights.PlayerPutEightNotification")
)

interface CrazyEightsCrazyEightsNotification : ProtocolDecksterNotification {


}

