/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = CrazyEightsDrawCardRequest::class, name = "CrazyEights.DrawCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsPassRequest::class, name = "CrazyEights.PassRequest"),
    JsonSubTypes.Type(value = CrazyEightsPutCardRequest::class, name = "CrazyEights.PutCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsPutEightRequest::class, name = "CrazyEights.PutEightRequest")
)

interface CrazyEightsCrazyEightsRequest : ProtocolDecksterRequest {


}

