/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = CrazyEightsCardResponse::class, name = "CrazyEights.CardResponse"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsFailureResponse::class, name = "CrazyEights.CrazyEightsFailureResponse"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsSuccessResponse::class, name = "CrazyEights.CrazyEightsSuccessResponse"),
    JsonSubTypes.Type(value = CrazyEightsPlayerViewOfGame::class, name = "CrazyEights.PlayerViewOfGame")
)

interface CrazyEightsCrazyEightsResponse : ProtocolDecksterResponse {


}

