/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param cards 
 * @param topOfPile 
 * @param currentSuit 
 * @param stockPileCount 
 * @param discardPileCount 
 * @param otherPlayers 
 */


data class CrazyEightsPlayerViewOfGame (

    @get:JsonProperty("type")
    override val type: kotlin.String? = null,

    @get:JsonProperty("cards")
    val cards: kotlin.collections.List<CommonCard>? = null,

    @get:JsonProperty("topOfPile")
    val topOfPile: CrazyEightsPutCardRequestAllOfCard? = null,

    @get:JsonProperty("currentSuit")
    val currentSuit: kotlin.String? = null,

    @get:JsonProperty("stockPileCount")
    val stockPileCount: kotlin.Int? = null,

    @get:JsonProperty("discardPileCount")
    val discardPileCount: kotlin.Int? = null,

    @get:JsonProperty("otherPlayers")
    val otherPlayers: kotlin.collections.List<CrazyEightsOtherCrazyEightsPlayer>? = null

) : CrazyEightsCrazyEightsResponse {


}

