/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name 
 * @param id 
 * @param points 
 */


data class HandshakeHelloSuccessMessageAllOfPlayer (

    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @get:JsonProperty("id")
    val id: kotlin.Any? = null,

    @get:JsonProperty("points")
    val points: kotlin.Int? = null

) {


}

