/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = HandshakeConnectFailureMessage::class, name = "Handshake.ConnectFailureMessage"),
    JsonSubTypes.Type(value = HandshakeConnectSuccessMessage::class, name = "Handshake.ConnectSuccessMessage"),
    JsonSubTypes.Type(value = HandshakeHelloSuccessMessage::class, name = "Handshake.HelloSuccessMessage")
)

interface HandshakeConnectMessage : ProtocolDecksterMessage {


}

