/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param player 
 * @param connectionId 
 */


data class HandshakeHelloSuccessMessage (

    @get:JsonProperty("type")
    override val type: kotlin.String? = null,

    @get:JsonProperty("player")
    val player: HandshakeHelloSuccessMessageAllOfPlayer? = null,

    @get:JsonProperty("connectionId")
    val connectionId: kotlin.Any? = null

) : HandshakeConnectMessage {


}

