/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = ChatRoomChatRequest::class, name = "ChatRoom.ChatRequest"),
    JsonSubTypes.Type(value = ChatRoomSendChatMessage::class, name = "ChatRoom.SendChatMessage"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsRequest::class, name = "CrazyEights.CrazyEightsRequest"),
    JsonSubTypes.Type(value = CrazyEightsDrawCardRequest::class, name = "CrazyEights.DrawCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsPassRequest::class, name = "CrazyEights.PassRequest"),
    JsonSubTypes.Type(value = CrazyEightsPutCardRequest::class, name = "CrazyEights.PutCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsPutEightRequest::class, name = "CrazyEights.PutEightRequest"),
    JsonSubTypes.Type(value = UnoDrawCardRequest::class, name = "Uno.DrawCardRequest"),
    JsonSubTypes.Type(value = UnoPassRequest::class, name = "Uno.PassRequest"),
    JsonSubTypes.Type(value = UnoPutCardRequest::class, name = "Uno.PutCardRequest"),
    JsonSubTypes.Type(value = UnoPutWildRequest::class, name = "Uno.PutWildRequest"),
    JsonSubTypes.Type(value = UnoReadyToPlayRequest::class, name = "Uno.ReadyToPlayRequest"),
    JsonSubTypes.Type(value = UnoUnoRequest::class, name = "Uno.UnoRequest")
)

interface ProtocolDecksterRequest : ProtocolDecksterMessage {


}

