/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = ChatRoomChatNotification::class, name = "ChatRoom.ChatNotification"),
    JsonSubTypes.Type(value = ChatRoomChatRequest::class, name = "ChatRoom.ChatRequest"),
    JsonSubTypes.Type(value = ChatRoomChatResponse::class, name = "ChatRoom.ChatResponse"),
    JsonSubTypes.Type(value = ChatRoomSendChatMessage::class, name = "ChatRoom.SendChatMessage"),
    JsonSubTypes.Type(value = CommonFailureResponse::class, name = "Common.FailureResponse"),
    JsonSubTypes.Type(value = CrazyEightsCardResponse::class, name = "CrazyEights.CardResponse"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsFailureResponse::class, name = "CrazyEights.CrazyEightsFailureResponse"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsNotification::class, name = "CrazyEights.CrazyEightsNotification"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsRequest::class, name = "CrazyEights.CrazyEightsRequest"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsResponse::class, name = "CrazyEights.CrazyEightsResponse"),
    JsonSubTypes.Type(value = CrazyEightsCrazyEightsSuccessResponse::class, name = "CrazyEights.CrazyEightsSuccessResponse"),
    JsonSubTypes.Type(value = CrazyEightsDrawCardRequest::class, name = "CrazyEights.DrawCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsGameEndedNotification::class, name = "CrazyEights.GameEndedNotification"),
    JsonSubTypes.Type(value = CrazyEightsGameStartedNotification::class, name = "CrazyEights.GameStartedNotification"),
    JsonSubTypes.Type(value = CrazyEightsItsYourTurnNotification::class, name = "CrazyEights.ItsYourTurnNotification"),
    JsonSubTypes.Type(value = CrazyEightsPassRequest::class, name = "CrazyEights.PassRequest"),
    JsonSubTypes.Type(value = CrazyEightsPlayerDrewCardNotification::class, name = "CrazyEights.PlayerDrewCardNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPassedNotification::class, name = "CrazyEights.PlayerPassedNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPutCardNotification::class, name = "CrazyEights.PlayerPutCardNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerPutEightNotification::class, name = "CrazyEights.PlayerPutEightNotification"),
    JsonSubTypes.Type(value = CrazyEightsPlayerViewOfGame::class, name = "CrazyEights.PlayerViewOfGame"),
    JsonSubTypes.Type(value = CrazyEightsPutCardRequest::class, name = "CrazyEights.PutCardRequest"),
    JsonSubTypes.Type(value = CrazyEightsPutEightRequest::class, name = "CrazyEights.PutEightRequest"),
    JsonSubTypes.Type(value = HandshakeConnectFailureMessage::class, name = "Handshake.ConnectFailureMessage"),
    JsonSubTypes.Type(value = HandshakeConnectMessage::class, name = "Handshake.ConnectMessage"),
    JsonSubTypes.Type(value = HandshakeConnectSuccessMessage::class, name = "Handshake.ConnectSuccessMessage"),
    JsonSubTypes.Type(value = HandshakeHelloSuccessMessage::class, name = "Handshake.HelloSuccessMessage"),
    JsonSubTypes.Type(value = ProtocolDecksterNotification::class, name = "Protocol.DecksterNotification"),
    JsonSubTypes.Type(value = ProtocolDecksterRequest::class, name = "Protocol.DecksterRequest"),
    JsonSubTypes.Type(value = ProtocolDecksterResponse::class, name = "Protocol.DecksterResponse"),
    JsonSubTypes.Type(value = UnoDrawCardRequest::class, name = "Uno.DrawCardRequest"),
    JsonSubTypes.Type(value = UnoGameEndedNotification::class, name = "Uno.GameEndedNotification"),
    JsonSubTypes.Type(value = UnoGameStartedNotification::class, name = "Uno.GameStartedNotification"),
    JsonSubTypes.Type(value = UnoItsYourTurnNotification::class, name = "Uno.ItsYourTurnNotification"),
    JsonSubTypes.Type(value = UnoPassRequest::class, name = "Uno.PassRequest"),
    JsonSubTypes.Type(value = UnoPlayerDrewCardNotification::class, name = "Uno.PlayerDrewCardNotification"),
    JsonSubTypes.Type(value = UnoPlayerPassedNotification::class, name = "Uno.PlayerPassedNotification"),
    JsonSubTypes.Type(value = UnoPlayerPutCardNotification::class, name = "Uno.PlayerPutCardNotification"),
    JsonSubTypes.Type(value = UnoPlayerPutWildNotification::class, name = "Uno.PlayerPutWildNotification"),
    JsonSubTypes.Type(value = UnoPlayerViewOfUnoGame::class, name = "Uno.PlayerViewOfUnoGame"),
    JsonSubTypes.Type(value = UnoPutCardRequest::class, name = "Uno.PutCardRequest"),
    JsonSubTypes.Type(value = UnoPutWildRequest::class, name = "Uno.PutWildRequest"),
    JsonSubTypes.Type(value = UnoReadyToPlayRequest::class, name = "Uno.ReadyToPlayRequest"),
    JsonSubTypes.Type(value = UnoUnoCardResponse::class, name = "Uno.UnoCardResponse"),
    JsonSubTypes.Type(value = UnoUnoCardsResponse::class, name = "Uno.UnoCardsResponse"),
    JsonSubTypes.Type(value = UnoUnoFailureResponse::class, name = "Uno.UnoFailureResponse"),
    JsonSubTypes.Type(value = UnoUnoGameNotification::class, name = "Uno.UnoGameNotification"),
    JsonSubTypes.Type(value = UnoUnoRequest::class, name = "Uno.UnoRequest"),
    JsonSubTypes.Type(value = UnoUnoResponse::class, name = "Uno.UnoResponse"),
    JsonSubTypes.Type(value = UnoUnoSuccessResponse::class, name = "Uno.UnoSuccessResponse")
)

interface ProtocolDecksterMessage {

    @get:JsonProperty("type")
    val type: kotlin.String?

}

