/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param color 
 * @param `value` 
 */


data class UnoUnoCardResponseAllOfCard (

    @get:JsonProperty("color")
    val color: kotlin.String? = null,

    @get:JsonProperty("value")
    val `value`: kotlin.String? = null

) {


}

