/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.forse.decksterlib.model

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * 
 *
 * @param type 
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = UnoDrawCardRequest::class, name = "Uno.DrawCardRequest"),
    JsonSubTypes.Type(value = UnoPassRequest::class, name = "Uno.PassRequest"),
    JsonSubTypes.Type(value = UnoPutCardRequest::class, name = "Uno.PutCardRequest"),
    JsonSubTypes.Type(value = UnoPutWildRequest::class, name = "Uno.PutWildRequest"),
    JsonSubTypes.Type(value = UnoReadyToPlayRequest::class, name = "Uno.ReadyToPlayRequest")
)

interface UnoUnoRequest : ProtocolDecksterRequest {


}

